# Subquestion 3: overall crash risk vs. injury and fatal crash risk

In [3]:
import pandas as pd

df = pd.read_csv("cleaned_data/05_analysis_ready_zh_motorways.csv")

print(df.shape)
df.head()

(1228, 28)

,VBN_ID,ROAD_DESCRIPTION,ROAD_NUMBER,ROAD_LENGTH_M,DIRECTION_BEGIN,DIRECTION_END,CARRIAGEWAY_TYPE_BEGIN,CARRIAGEWAY_TYPE_END,HAS_TRAFFIC_DATA,AVG_DAILY_TRAFFIC,...,TRAFFIC_COVERAGE_PCT,ANNUAL_VEHICLE_KM,TOTAL_CRASHES,MATERIAL_DAMAGE_CRASHES,INJURY_CRASHES,FATAL_CRASHES,INJURY_FATAL_CRASHES,CRASH_RATE_PER_100M_VKM,INJURY_FATAL_RATE_PER_100M_VKM,GEOMETRY_WKT
0,10000000001492700860,A15 b (OPR) Havens 5500-5600,A15,45.0,Re,Re,OPR,OPR,1,250.0,...,100.0,4106.25,0,0,0,0,0,0.000000,0.0,"LINESTRING (74567.64199 435285.76651, 74568.62..."
1,10000000001512701040,A15 b (OPR) Rozenburg,A15,97.0,Re,Re,OPR,OPR,1,3100.0,...,100.0,109755.50,0,0,0,0,0,0.000000,0.0,"LINESTRING (75525.972 435244.552, 75528.06123 ..."
2,10000000001512701050,A15 d (OPR) ROZENBURG,A15,140.0,Li,Li,OPR,OPR,1,2800.0,...,100.0,143080.00,0,0,0,0,0,0.000000,0.0,"LINESTRING (75723.8393445015 435362.893433999,..."
3,10000000001512810410,A20 b (OPR) Maasdijk-Oost,A20,378.0,Re,Re,OPR,OPR,1,6100.0,...,100.0,841617.00,1,1,0,0,0,118.818893,0.0,"LINESTRING (75556.498 441053.268, 75575.046100..."
4,10000000001512820560,A20 d (OPR) Maasdijk-Oost,A20,377.0,Li,Li,OPR,OPR,1,3900.0,...,100.0,536659.50,0,0,0,0,0,0.000000,0.0,"LINESTRING (75658.233 441162.014, 75654.673099..."

In [4]:
cols = [
    "TOTAL_CRASHES",
    "INJURY_CRASHES",
    "FATAL_CRASHES",
    "INJURY_FATAL_CRASHES",
    "ANNUAL_VEHICLE_KM"
]

df[cols].describe()

,TOTAL_CRASHES,INJURY_CRASHES,FATAL_CRASHES,INJURY_FATAL_CRASHES,ANNUAL_VEHICLE_KM
count,1228.000000,1228.000000,1228.000000,1228.000000,1.223000e+03
mean,5.938925,0.575733,0.008958,0.584691,9.667162e+06
std,13.136808,1.598175,0.094258,1.604850,1.826742e+07
min,0.000000,0.000000,0.000000,0.000000,2.861600e+03
25%,0.000000,0.000000,0.000000,0.000000,7.273902e+05
50%,1.000000,0.000000,0.000000,0.000000,2.656288e+06
75%,5.000000,0.000000,0.000000,0.000000,1.073615e+07
max,159.000000,24.000000,1.000000,24.000000,1.888850e+08